name: farmodo
description: "Pomodoro Timer : Focus & Farm"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.5.1+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  percent_indicator: ^4.2.5
  get_it: ^8.2.0
  hugeicons: ^0.0.11
  iconsax: ^0.0.8
  google_sign_in: ^6.2.1
  lottie: ^3.3.1
  very_good_analysis: ^9.0.0
  flame: ^1.32.0
  flutter_launcher_icons: ^0.14.4
  kartal: ^4.2.0
  adapty_flutter: ^3.11.3

  #Local
  sqflite: ^2.4.2

  #Auth
  sign_in_with_apple: ^7.0.1 

  #Utility
  logger: ^2.6.1
  home_widget: ^0.8.0
  live_activities: ^1.9.5
  shared_preferences: ^2.3.2
  flutter_local_notifications: ^17.2.2
  permission_handler: ^11.3.1
  audioplayers: ^6.5.1
  easy_localization: ^3.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app/ic_launcher.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/animals/
    - assets/images/actions/
    - assets/images/cover/
    - assets/images/onboard/
    - assets/logo/
    - assets/lottie/
    - assets/icons/
    - assets/icons/achievements/
    - assets/sounds/
    - assets/translations/
    - assets/purchase_items/coin/
    - assets/purchase_items/lottie/
    - assets/purchase_items/lottie/pack_icon/

    
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
