name: farmodo
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  percent_indicator: ^4.2.5
  get_it: ^8.2.0
  hugeicons: ^0.0.11
  iconsax: ^0.0.8
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/logo/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter_18pt-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter_18pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter_18pt-ExtraBold.ttf
          weight: 800
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
